### PR TITLE
Fix for systems where size_t is not at least 64-bit, declare schedule array w in the right place

### PR DESCRIPTION
**Pull request by jan2000**

### CODE REVIEW

**Comment by amosnier** [comment]
I have two issues with this pull request:
- The implementation would suddenly no longer work with C89 compilers that have no support for `uint64_t`. I have to admit that in the current state, the implementation is not totally clear on its limitations. One could have `sizeof(size_t) == sizeof(uint32_t)` and converting the original length into a number of bits then could silently overflow. Users should test the implementation on their platform, and not use input which is larger than the larger validated test data. The `LARGE_MESSAGES` flag helps with that. Basically I do not really wish to introduce `uint64_t` in this implementation. Do you have a concrete case of a platform where you are lacking that, or is it just a matter of principle?
- When it comes to "declare schedule array w in the right place", could you please explain what you mean? In my book, the right place is where it minimizes scope. According to that principle, your change is, as far as I can see, for the worse.

**Comment by jan2000** [comment]
I was having problems with the previous commit I made on mips32r2 ISA where indeed `sizeof(size_t) == sizeof(uint32_t)`. With `len = 16` I got `0000008000000080` instead of `0000000000000080` for `total_len`, probably because the shift overflows 32. So a simple fix was to cast to `uint64_t`, but I was not aware that is non C89 and should be avoided. Probably better then to revert to the approach before my previous pull request, but use a copy of the `len` value.

Regarding the `w` array, currently it is problematic: on line 127 `w` is declared and then on line 136 `w` is read without being initialized. An code analyzer could see this as undefined behaviour. I am not sure what the standard exactly says about this. See for example this question https://stackoverflow.com/q/64525770

**Comment by amosnier** [comment]
Effectively, your #6 did break my carefully crafted and clearly commented "Storing of len * 8 as a big endian 64-bit without overflow". The whole idea of this implementation is indeed to make no assumption about the user's machine, apart from those strictly required by the implementation. I will now revert the merge of that pull request.

On the other hand, access to the `w` array is indeed undefined behavior. I was not aware of that, but [ISO/IEC 9899:TC3](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf) is perfectly clear about it in 6.2.4 Storage durations of objects:  

> The initial value of the object [with automatic storage duration] is indeterminate. If an initialization is specified for the object, it is performed each time the declaration is reached in the execution of the block; otherwise, **the value becomes indeterminate each time the declaration is reached**.

Emphasis is mine. Thanks for pointing this out, I will correct it.

**Comment by amosnier** [comment]
I encouraged you to submit a new pull request which would keep the careful handling of the length parameter without narrowing, and your performance improvement. I will now close this pull request. Thanks again.

**Pull request closed without merging**
